export const fakeRequestHeaders = {
    Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,zh-TW;q=0.5',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
    Cookie: 'VuY827dYrD6VO=60opTfvlkMQ5GkREc2fScNYuKUWjowAV128pl3eCaQZdopwKlYmjZ15QHmjea_GAJi_JtLSEX.TJ4iEMhin9HgIA; enable_VuY827dYrD6V=true; JSESSIONID=5D93C795C30EF92DAA47D3028CE4CAD8; VuY827dYrD6VP=0DYvsTkfZkPM6ydb7cxv6O3zKeemx9Xdo5clzc4cRYOMLxt8se2GPoxiNkyemnWm1CMNKwo_KNhAYoXBOfus0bumKWZ_iu6YPJ2UJRiK1y8VSUzNMzYbPJNOC4oz3xxb3Y_EpGvVmUXzB8OjCgPJtpUoqKBj85ES2gvtQnFzDeWlPC7Br6cudkONjz_yQlgnQMy45qQt7LSd.Sq.KaroNGqd1SBgD2oDPRzpzPOy.EY6be9H7orUZLv2FKFwNg2R_wvtElcAEINw8rShOUaNkezH7JddZVgeUPUjvvrXxDaDkHknBi4O7hXsKFGryyXx3qm3TWXDt5ty1vjGx_uIqgKZvJuzNl.jS1.zxC2JGlgic0eDVb9Nh_c1Cv.L457LHJTvJ.4Qbuznjpuxy4E0s4d0bFXeBuHQyDayWXDwVarV',
    Host: 'www.lzu.edu.cn',
    Pragma: 'no-cache',
    Referer: 'https://www.lzu.edu.cn/',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-User': '?1',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0',
    'sec-ch-ua': `"Microsoft Edge";v="131", "Chromium";v="131", "Not_A Brand";v="24"`,
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': `"Windows"`,
};
